apiVersion: apps/v1
kind: Deployment
metadata:
  name: angular1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: angular1
  template:
    metadata:
      labels:
        app: angular1
    spec:
      containers:
      - name: angular1
        image: gcr.io/oceanic-craft-302516/angular1:latest
        ports:
        - containerPort: 80
        imagePullPolicy: Always