apiVersion: apps/v1
kind: Deployment
metadata:
  name: angular
spec:
  replicas: 1
  selector:
    matchLabels:
      app: angular
  template:
    metadata:
      labels:
        app: angular
    spec:
      containers:
      - name: angular
        image: gcr.io/oceanic-craft-302516/angular:latest
        ports:
        - containerPort: 80
        imagePullPolicy: Always