apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  ports:
  - name: http
      protocol: TCP
      port: 80
      targetPort: 80
    - name: https
      protocol: TCP
      port: 443
      targetPort: 80

  selector:
    app: frontend
  type: LoadBalancer